"""Cross-platform gates (Windows in particular).

The CLI is developed and released from Linux, so every platform assumption
it makes is invisible here until a Windows user hits it. Each test below
pins one such assumption by reproducing the Windows condition on any
platform:

* stdout encoding — Windows uses the ANSI code page for a *redirected*
  stdout (a console gets UTF-8), so the documented
  ``pcp agents >> AGENTS.md`` step silently writes non-UTF-8 bytes and a
  Chinese capsule dies with ``UnicodeEncodeError``. Reproduced with
  ``PYTHONIOENCODING``, which drives the same code path.
* line endings — Git for Windows checks out with ``core.autocrlf=true`` by
  default, so a byte-pinned fixture arrives as CRLF while the generator
  always writes LF. Checked by asking git what it will actually do.
* path display — every repository-relative path this tool reports is
  forward-slashed (``loader`` and ``generator`` all end in ``as_posix``);
  the one place that used ``str()`` reported ``.planning\\dist`` on Windows.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import PureWindowsPath

import pytest

from planning_control_plane import cli as cli_module

from conftest import REPO_ROOT


def _run(*argv: str, encoding: str, cwd=None) -> subprocess.CompletedProcess:
    """Run the CLI in a subprocess whose stdout uses *encoding*.

    A subprocess is required: the ambient stdout encoding is exactly what is
    under test, and the in-process ``cli`` fixture replaces the stream.
    """
    env = dict(os.environ, PYTHONIOENCODING=encoding)
    return subprocess.run(
        [sys.executable, "-m", "planning_control_plane.cli", *argv],
        cwd=cwd,
        env=env,
        capture_output=True,
    )


def _utf8(raw: bytes, what: str) -> str:
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        pytest.fail(f"{what} is not valid UTF-8: {exc}")


@pytest.mark.parametrize("encoding", ["cp1252", "cp936"])
def test_agents_snippet_stays_utf8_under_a_legacy_stdout_encoding(encoding):
    """``pcp agents >> AGENTS.md`` is the onboarding step ``pcp init``
    prints, so it always redirects. The appended block must be UTF-8 — that
    is how every AI harness reads AGENTS.md — no matter what encoding the
    ambient stdout carries.
    """
    result = _run("agents", encoding=encoding)
    assert result.returncode == 0
    assert cli_module._AGENTS_SNIPPET in _utf8(result.stdout, "pcp agents stdout")


def test_context_capsule_survives_a_legacy_stdout_encoding(make_project, node_dict, tmp_path):
    """A Chinese project used from an English Windows: the capsule is
    redirected into a file, and cp1252 cannot encode the node title. The
    command must still succeed and emit UTF-8.
    """
    _project, root = make_project(
        tmp_path,
        config_dict={
            "project": {"id": "t", "name": "T"},
            "planning": {"current_focus": "P1"},
        },
        node_dicts=[node_dict("P1", title="中文标题", objective="验证编码")],
    )
    result = _run("-p", str(root), "context", "P1", encoding="cp1252")
    assert result.returncode == 0, result.stderr.decode("utf-8", "replace")
    assert "中文标题" in _utf8(result.stdout, "pcp context stdout")


# ------------------------------------------------------------- line endings


def _git_attr(path: str, attr: str) -> str:
    """What git will apply to *path* for *attr* in this working tree."""
    result = subprocess.run(
        ["git", "check-attr", attr, "--", path],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        pytest.skip(f"git unavailable: {result.stderr.strip()}")
    # Output shape: "<path>: <attr>: <value>"
    return result.stdout.rsplit(": ", 1)[-1].strip()


def test_byte_pinned_fixtures_are_checked_out_with_lf():
    """``generator._write_text`` pins ``newline="\n"``, and
    ``test_ideas_ui`` compares generated bytes against this fixture byte for
    byte. Without a checkout rule the Git for Windows default
    (``core.autocrlf=true``) turns the fixture into CRLF and that gate fails
    on Windows only.
    """
    # ``unset`` is what ``-text`` yields: git converts nothing, in either
    # direction, on any platform.
    assert _git_attr("tests/fixtures/phase1_style.css", "text") == "unset"


# ------------------------------------------------------------- path display


def test_output_directory_display_is_forward_slashed_on_windows():
    """``pcp build`` reports where it wrote. Repository-relative paths are
    forward-slashed on every platform — the convention the loader already
    follows for the ``source`` strings it records — so the same project
    reads the same way from Linux and Windows.
    """
    assert (
        cli_module._output_display(
            PureWindowsPath(r"D:\repo\.planning\dist"), PureWindowsPath(r"D:\repo")
        )
        == ".planning/dist"
    )


def test_output_directory_outside_the_root_is_shown_as_the_platform_writes_it():
    """A directory configured outside the repository has no
    repository-relative form; there is nothing to normalize, so it is shown
    verbatim rather than posix-ified into something that is not a path on
    that platform.
    """
    assert (
        cli_module._output_display(
            PureWindowsPath(r"E:\out"), PureWindowsPath(r"D:\repo")
        )
        == "E:\\out"
    )
